### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by louis842** [LachlanDev/TikTok-Utilities#1]
I have no idea how to start the bot please could you tell me?

**Comment by LachlanDev** [comment]
If you would like to use the Discord BOT on your server use this [link](https://discord.com/oauth2/authorize?client_id=779968259671457792&scope=bot&permissions=93248) to invite it . The purpose of this source code is for contributions meaning people help with the development of the application. If you don't have a basic knowledge of Discord BOT development you shouldn’t need to access the source code. If you want to get started with BOT development have a look [here](https://github.com/PapaSnags/Discord-BOT-Template).
