### ISSUE TITLE
DiscordAPIError: Cannot send an empty message

### ISSUE THREAD

**Issue by ghost** [LachlanDev/TikTok-Utilities#3]
I got this error:

DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (/home/pi/IT-Network2.0/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async RequestHandler.push (/home/pi/IT-Network2.0/node_modules/discord.js/src/rest/RequestHandler.js:50:14) {
  method: 'post',
  path: '/channels/851049925818580992/messages',
  code: 50006,
  httpStatus: 400,
  requestData: {
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined
    },
    files: []
  }
}

**Comment by LachlanDev** [comment]
What command are you executing ?

**Comment by ghost** [comment]
Profile command but other commands aren’t working too

**Comment by ghost** [comment]
Are you updating everything?

**Comment by LachlanDev** [comment]
Sorry for the late reply, I haven't had the chance to work on an update for TikTok utilities and as of now I don't plan on it in the future. If you want to contribute to the project with updates feel free to open a pull request with the changes clearly labeled.
Thanks!
